[project]
name = "py_base_project"
authors = [
    { name = "ByteStreamHub team", email = "thiago@thir.info" }
]
maintainers = [
    { name = "Thiago Augusto Dias", email = "thiago@thir.info" }
]
version = "0.1.1"
description = "This project is a framework to be a template for Python projects."
readme = "README.md"

requires-python = ">=3.10"

dependencies = [
 "aws-cdk-aws-appsync-alpha>=2.59.0a0",
 "aws-cdk-lib>=2.210.0",
 "jinja2>=3.1.6",
 "structlog>=25.4.0",
]

[dependency-groups]
dev = [
 "pyright>=1.1.403",
 "commitizen>=4.8.3",
 "pre-commit>=4.2.0",
 "pytest-cov>=6.2.1",
 "setuptools>=61.0",
 "pytest>=8.4.1",
 "ruff>=0.12.7",
 "git-changelog>=1.0.0",

]

[tool.pyright]
include = ["src"]
exclude = [
    "**/__pycache__",
    "src/experimental",
    "src/typestubs",
    "local-dev",
]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.10"

executionEnvironments = [
  { root = "src" }
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools.packages.find]
where = ["src"]
include  = ["*"]

[tool.ruff]
include = ["*.py", "*.py.j2"]
