convention="conventional"
provider="github"
template="keepachangelog"
sections = [
    "build",
    "chore",
    "ci",
    "deps",
    "doc",
    "feat",
    "fix",
    "revert",
    "refactor",
    "test"
]
versioning="semver"
parse_trailers=true
parse_refs=false
